[package]
name = "manx"
version = "0.1.0"
authors = ["kevlarr <echo1+git@dvnl.net>"]
edition = "2018"

[dependencies]
actix-web = "0.7.17"
diesel = { version = "1.3.3", features = ["postgres", "uuid"] }
dotenv = "0.10.1"
serde = "1.0.84"
serde_derive = "1.0.84"
